export enum BASE_HTTP_CODE {
  UNKNOWN = -1,
  SUCCESS = 0,
  DEFAULT_ERROR = 500,
  PARAM_ERROR = 400,
  AUTH_FAILURE = 401,
  NO_PERMISSION = 403,
}

export enum ERROR_HTTP_CODE {
  PARAM_INVALID = 40000,
}

export const HTTP_CODE_MSG = {
  [BASE_HTTP_CODE.UNKNOWN]: '未知错误',
  [BASE_HTTP_CODE.SUCCESS]: '请求成功',
  [BASE_HTTP_CODE.DEFAULT_ERROR]: '服务器错误',
  [BASE_HTTP_CODE.PARAM_ERROR]: '参数错误',
  [BASE_HTTP_CODE.AUTH_FAILURE]: '身份校验错误',
  [BASE_HTTP_CODE.NO_PERMISSION]: '权限错误',
  [ERROR_HTTP_CODE.PARAM_INVALID]: '参数错误',
} as Record<BASE_HTTP_CODE, string>;
